config/routes.rb
Rentroll::Application.routes.draw do

  root :to => 'home#index'

  resources :properties do
    resources :units
  end

  match '/assumptions' => 'home#assumptions', :as => :assumptions
  match '/update' => 'home#update_assumptions', :as => :update_assumptions

end

app/models/property.rb
require 'SomeLogic'

class Property < ActiveRecord::Base
  include SomeLogic
  attr_accessible :address
  validates :address, :presence => true, :uniqueness=> {:case_sensitive => false}
  has_many :units, :dependent => :destroy

  #scope :processed, where("fulfilled =? OR canceled = ?",true,true)
  #scope :pending, where("fulfilled =? AND canceled = ?",false,false)

  #STATES=%w{AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY}
  #validates :address, :city, :email, :name, :state, :zip, :presence => true
  #validates :state, :inclusion => STATES
  #validates :email, :format=>{:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  #validates :zip, :format=>{:with => /^\d{5}$/}

  #def get_states
  # 	STATES
  # end

  #def get_total
  #  line_items.to_a.sum{|l| l.total_price}
  #end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :current_rent, :move_in, :property_id, :unumber
  validates :current_rent, :move_in, :unumber, :presence=>true
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :setup_assumptions

private
  def setup_assumptions
  	if session[:assumptions].nil?
  		session[:assumptions] = {:market_rent=>20,:relocate=>0.4}
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if params[:query] && params[:query].size
      @properties = Property.where("address LIKE ?", "%#{params[:query]}%").order(sort_column).paginate(:page => params[:page], :per_page => 5)
    else
  	 @properties = Property.order(sort_column).paginate(:page => params[:page], :per_page => 5)
    end
  	@property = Property.new
    @somevar = @property.some_calc
  end

  def assumptions
  	@assumptions = session[:assumptions]
  end

  def update_assumptions
  	session[:assumptions][:market_rent] = params[:market_rent]
  	session[:assumptions][:relocate] = params[:relocate]
  	#render :text => params.inspect
  	redirect_to assumptions_url
  end

  private

  def sort_column
    params[:sort] || "address"
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	def create
		property = Property.new(params[:property])
		property.save
		session[:errors]=property.errors
		redirect_to root_url
	end

	def show
		@property = Property.find(params[:id])
		@units = @property.units.all
		@unit = @property.units.new
		@ttl = @property.units.sum(:current_rent)
		@total = 0
		if @units.size!=0
			@units.each do |u|
				@total+=u.current_rent
			end
		end
	end

	def destroy
		@property = Property.find(params[:id])
		@property.destroy
		redirect_to root_url
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
	def create
		property = Property.find(params[:property_id])
		unit = property.units.new(params[:unit])
		unit.save
		redirect_to property_url(property)
	end

	def destroy
		property = Property.find(params[:property_id])
		unit = property.units.new(params[:unit])
		unit.destroy
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/home/assumptions.html.erb
<h3>Edit Assumptions</h3>
<%=form_tag update_assumptions_url do %>
Market Rent: <%=text_field_tag :market_rent, @assumptions[:market_rent]%><br>
Relocate: <%=text_field_tag :relocate, @assumptions[:relocate]%><br>
<%=submit_tag "Update", :class=>"btn"%>
<%end%>

app/views/home/index.html.erb
<h3>Add a Property:</h3>
<%=form_for @property, :html=>{:class=>"form-inline"} do |f|%>
	<%if session[:errors] && session[:errors].any?%>
		<div class="alert alert-error">
	  		<button type="button" class="close" data-dismiss="alert">&times;</button>
	  		<strong>Error!</strong> Address <%=session[:errors].messages[:address][0]%>
		</div>
	<%end%>
Address: <%=f.text_field :address%>
<%=f.submit "Add", :class=>"btn"%>
<%end%>

<h3>All Properties <span class="muted">(<%=Property.all.size%> properties)</span></h3>
<table class="table table-condensed table-hover">
	<tr>
		<th>
			<%if params[:sort]!="id"%>
			<%=link_to "ID", params.merge(:sort=>"id",:page=>nil)%>
			<%else%>
			ID
			<%end%>
		</th>
		<th>
			<%if params[:sort]!="address"%>
			<%=link_to "Address", params.merge(:sort=>"address",:page=>nil)%>
			<%else%>
			Address
			<%end%>
		</th>
	</tr>
<%@properties.each do |p|%>
	<tr>
		<td><%=p.id%></td>
		<td><%=link_to "#{p.address}", property_url(p)%> (<%=link_to "delete", property_url(p), :method=>:delete, :confirm=>"Are you sure?", :class=>"muted"%>)</td>
	</td>
<%end%>
</table>
<%= will_paginate @properties %>

<%=@somevar%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentroll</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">RentRoll</a>
    <ul class="nav">
      <li><%=link_to "Home", root_url%></li>
      <li><%=link_to "Assumptions", assumptions_url%></li>
    </ul>
    <%=form_tag root_url, :class=>"navbar-search pull-left" do %>
      <%=text_field_tag :query, params[:query], :class=>"search-query", :placeholder=>"Search"%>
      <%=hidden_field_tag :sort, params[:sort]%>
    <%end%>
  </div>
</div>
<%= yield %>
</div>
</body>
</html>

app/views/properties/show.html.erb
<h3><%=@property.address%> <span class="muted">(<%=link_to "edit", edit_property_url(@property), :class=>"muted"%>)</span></h3>
<%if @units.size!=0%>
	<table class="table table-condensed table-hover">
		<tr>
			<td>Unit #</td>
			<td>Move-in</td>
			<td>Current Rent</td>
		</tr>
	<%@units.each do |u|%>
		<tr>
			<td><%=u.unumber%></td>
			<td><%=u.move_in%></td>
			<td><%=number_to_currency(u.current_rent)%></td>
		</tr>
	<%end%>
	</table>
<h3>Analysis</h3>
	Total: <%=number_to_currency(@total)%>
	<%else%>
	<p class="muted">No units to display</p>
<%end%>
<h3>Add Unit</h3>
<%=form_for [@property,@unit], :html=>{:class=>"form-horizontal"} do |f|%>
	<div class="control-group">
		<%=f.label :unumber,"Unit",:class=>"control-label"%>
		<div class="controls">
			<%=f.text_field :unumber%>
		</div>
	</div>
	<div class="control-group">
		<%=f.label :unumber,"Move-in",:class=>"control-label"%>
		<div class="controls">
			<%=f.date_select :move_in%>
		</div>
	</div>
	<div class="control-group">
		<%=f.label :unumber,"Current Rent",:class=>"control-label"%>
		<div class="controls">
			<%=f.text_field :current_rent%>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<%=f.submit "Add Unit", :class=>"btn"%>
		</div>
	</div>
<%end%>
<h1><%=number_to_currency(@ttl)%></h1>